### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getWorkingDirectory' of null

### ISSUE THREAD

**Issue by dcrystalj** [gschrader/tabs-closer#5]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0-beta1 x64
**Electron**: 1.3.14
**OS**: Linux Mint
**Thrown From**: [tabs-closer](https://github.com/gschrader/tabs-closer) package 0.14.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getWorkingDirectory' of null

```
At /home/dcrystalj/.atom/packages/tabs-closer/lib/tabs-closer.coffee:14

TypeError: Cannot read property 'getWorkingDirectory' of null
    at Object.tabInRepo (/packages/tabs-closer/lib/tabs-closer.coffee:14:33)
    at /packages/tabs-closer/lib/tabs-closer.coffee:19:84)
    at Object.closeUnmodifiedTabs (/packages/tabs-closer/lib/tabs-closer.coffee:19:7)
    at /packages/tabs-closer/lib/tabs-closer.coffee:4:82)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom-beta/resources/app/src/command-registry.js:265:1)
    at CommandRegistry.handleCommandEvent (/usr/share/atom-beta/resources/app/src/command-registry.js:3:1)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom-beta/resources/app/src/command-registry.js:166:1)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/usr/share/atom-beta/resources/app/src/atom-environment.js:1292:1)
    at EventEmitter.outerCallback (/usr/share/atom-beta/resources/app/src/application-delegate.js:347:1)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -3:37.8.0 core:save (input.hidden-input)
     -3:37.4.0 core:close (input.hidden-input)
     -3:34.9.0 pane:show-next-recently-used-item (input.hidden-input)
     -3:34.1.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
     -0:33.7.0 intentions:highlight (input.hidden-input)
     -0:33.6.0 pane:show-next-recently-used-item (input.hidden-input)
     -0:33.1.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
     -0:32.6.0 intentions:highlight (input.hidden-input)
  3x -0:32.5.0 pane:show-next-recently-used-item (input.hidden-input)
     -0:31.1.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
     -0:31 intentions:highlight (input.hidden-input)
     -0:30.9.0 pane:show-previous-recently-used-item (input.hidden-input)
     -0:30.3.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
     -0:29 intentions:highlight (input.hidden-input)
     -0:28.9.0 core:close (input.hidden-input)
  2x -0:24.2.0 tabs-closer:close-unmodified-tabs (li.texteditor.tab.sortable.right-clicked)
```

### Non-Core Packages

```
accents-ui 1.3.0 
aligner 0.22.3 
an-old-hope-syntax 1.0.4 
atom-django 0.3.2 
atom-jinja2 0.6.0 
autocomplete-ansible 0.1.11 
autocomplete-paths 1.0.5 
autocomplete-python 1.8.63 
busy-signal 1.3.0 
close-tags 0.6.0 
color-picker 2.2.5 
count-word 0.2.3 
django-atom 0.2.4 
django-templates 0.5.0 
docker 0.7.0 
dracula-theme 2.0.3 
dracula-ui 0.4.1 
es6-javascript 1.0.0 
genesis-ui 0.5.0 
gist 0.4.0 
git-time-machine 1.5.9 
hidpi 0.12.0 
highlight-selected 0.13.1 
increment-selection 0.3.0 
intentions 1.1.2 
javascript-snippets 1.2.1 
jsartisan-dark-minimalistic-ui 2.3.0 
language-ansible 0.2.1 
language-docker 1.1.7 
language-latex 1.0.0 
language-lisp 0.2.0 
language-markdown 0.21.0 
language-vue 0.21.2 
latex 0.43.0 
latex-autocomplete 1.0.0 
lint 0.0.1 
linter 2.1.4 
linter-ansible-linting 1.2.3 
linter-docker 0.2.0 
linter-pylama 0.8.16 
linter-python 3.1.1 
linter-python-pep8 0.2.0 
linter-ui-default 1.2.3 
open-recent 5.0.0 
pdf-view 0.57.0 
pigments 0.39.1 
process-palette 0.12.0 
python-indent 1.0.2 
quick-editor 0.4.3 
script 3.14.1 
set-syntax 0.3.2 
sourcerer 2.0.0 
Spectacular 1.1.0 
sync-settings 0.8.1 
tab-control 0.6.10 
tabs-closer 0.14.0 
tabs-to-spaces 1.0.3 
tasks 2.6.6 
vue-snippets 0.6.0 
```

**Comment by gschrader** [comment]
fixed in 0.15.0
